# Host to use for canonical URL generation (without trailing slash)
host: /

# Header-related options
show_govuk_logo: false
service_name: Accessibility Issues
service_link: https://alphagov.github.io/accessibility-issues/
phase: Alpha

# Links to show on right-hand-side of header
header_links:
  # About: https://alphagov.github.io/accessibility-issues/about/
  GitHub: https://github.com/alphagov/accessibility-issues

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 6

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true

# Show a block at the bottom of the page that links to the page source
show_contribution_banner: true
github_repo: alphagov/accessibility-issues
